### ISSUE TITLE
index entry for topic/ROV _ one/RTI/body _ velocity/rawcontains invalid time

### ISSUE THREAD

**Issue by WLXM0922** [jake3991/DRACo-SLAM#3]
Hello, thank you very much for your work, but I have a problem when running this project, as follows:                                                           When I run rosbag playsample _ data _ three _ robot.bag, I get an error:                                                                                                     Error:  index entry for topic/ROV _ one/RTI/body _ velocity/rawcontains invalid time. This message will not be loaded.
at line 651 in /tmp/binarydeb/ros-noetic-rosbag-storage-1.16.0/src/bag.cpp
Error:   Index entry for topic /rov_two/vn100/imu/raw contains invalid time.  This message will not be loaded.
at line 651 in /tmp/binarydeb/ros-noetic-rosbag-storage-1.16.0/src/bag.cpp
Error:   Index entry for topic /rov_three/vn100/imu/raw contains invalid time.  This message will not be loaded.
at line 651 in /tmp/binarydeb/ros-noetic-rosbag-storage-1.16.0/src/bag.cpp

**Comment by wqklihbf** [comment]
Hello, I have meet the same question: Error:   Index entry for topic /velodyne_points_0 contains invalid time.  This message will not be loaded.
at line 649 in /tmp/binarydeb/ros-melodic-rosbag-storage-1.14.13/src/bag.cpp
How do you solve it?

**Comment by jake3991** [comment]
Why is there a velodyne topic? That seems out of scope.

**Comment by wqklihbf** [comment]
> Why is there a velodyne topic? That seems out of scope.

Sorry, I'm actually running a different SLAM system (I2EKF-LO) and encountered this issue. While searching for a solution, I came across someone who had a very similar problem, so I just wanted to ask about it.

**Comment by WLXM0922** [comment]
> > Why is there a velodyne topic? That seems out of scope.
> 
> Sorry, I'm actually running a different SLAM system (I2EKF-LO) and encountered this issue. While searching for a solution, I came across someone who had a very similar problem, so I just wanted to ask about it.

Hello, this problem may be because there is no simulation time when running rosbag. Please try adding --clock after rosbag play.
